include: package:lints/recommended.yaml

page_formatter:
  width: 80

analyzer:
  exclude:
    - '**/*.mapper.dart'
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - package_api_docs
    - public_member_api_docs
    - sort_pub_dependencies
