include: package:lints/recommended.yaml

analyzer: 
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - package_api_docs
    - public_member_api_docs
    - sort_pub_dependencies
