include: package:lints/recommended.yaml

analyzer: 
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - package_api_docs
    - public_member_api_docs
    - sort_pub_dependencies
