name: Build

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
      code-gen:
        required: true
        type: bool

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        working-directory: ${{ inputs.dir }}
        run: dart pub get
          
      - name: Run build_runner
        if: ${{ inputs.code-gen }}
        working-directory: ${{ inputs.dir }}
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Ensure clean git status
        run: ../tool/ensure_git_clean.sh

      - name: Verify formatting
        working-directory: ${{ inputs.dir }}
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        uses: invertase/github-action-dart-analyzer@v1
        with:
          working-directory: ${{ inputs.dir }}

      - name: Run tests and generate coverage report
        working-directory: ${{ inputs.dir }}
        run: ../../tool/generate_code_coverage.sh

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1.4.0
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 90
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: code-coverage-report
          working-directory: ${{ inputs.dir }}