name: Build

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
      min-pana-score:
        required: true
        type: number

jobs:
  pana:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2.3.5
        - uses: dart-lang/setup-dart@v1.3

        - name: Install dependencies
          working-directory: ${{ inputs.dir }}
          run: |
            dart pub get
            dart pub global activate pana
        
        - name: Verify pub score
          working-directory: ${{ inputs.dir }}
          run: ../../tool/verify_pub_score.sh ${{ inputs.min-pana-score }}