name: Build

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      code-gen:
        required: true
        type: boolean
      min-pana-score:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        working-directory: packages/${{ inputs.package-name }}
        run: dart pub get
          
      - name: Run build_runner
        if: ${{ inputs.code-gen }}
        working-directory: packages/${{ inputs.package-name }}
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Ensure clean git status
        run: ./tool/ensure_git_clean.sh

      - name: Verify formatting
        working-directory: packages/${{ inputs.package-name }}
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        uses: invertase/github-action-dart-analyzer@v1
        with:
          working-directory: packages/${{ inputs.package-name }}

      - name: Run tests and generate coverage report
        working-directory: packages/${{ inputs.package-name }}
        run: ../../tool/generate_code_coverage.sh ${{ inputs.package-name }}-lcov.info

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.package-name }}-code-coverage
          path: packages/${{ inputs.package-name }}/coverage/${{ inputs.package-name }}-lcov.info

  pana:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2.3.5
        - uses: dart-lang/setup-dart@v1.3

        - name: Install dependencies
          working-directory: packages/${{ inputs.package-name }}
          run: |
            dart pub get
            dart pub global activate pana
        
        - name: Verify pub score
          working-directory: packages/${{ inputs.package-name }}
          run: ../../tool/verify_pub_score.sh ${{ inputs.min-pana-score }}
